### ISSUE TITLE
Multisources dont work so good as Masters

### ISSUE THREAD

**Issue by CryoKeen** [SamVanheer/HLEnhanced-Game#2]
hey great to see progress on this so cool! im trying the sectore map in it, not sure if this is a hl1 bug or not yet, but in your version a multisource will not work as follows:

multiple buttons targeting a single multisource not properly activating Master condition like func_button still locked or trigger_teleport not toggleing on/off with a multi_manager

**Comment by SamVanheer** [comment]
You're probably using Sven Co-op specific features in your maps. Remember, vanilla HL relies on masters only and will not unlock entities by triggering them. Teleports in SC can be toggled by triggering them.

**Comment by CryoKeen** [comment]
That's probably true

however, would you consider adding some backwards compatibility into your new mod? a lot of people want to leave svencoop but have no where to go. its doubtful you could be sued.

**Comment by SamVanheer** [comment]
As i have said before, i am not trying to replace Sven Co-op or be competitive with them. I will not implement compatibility with their maps.

**Comment by SamVanheer** [comment]
There was a bug in multisource that could have caused this, am fixing it now.

**Comment by SamVanheer** [comment]
I've committed new libraries, should be fixed now. Try it out again and see if it works, let me know how it goes.

**Comment by CryoKeen** [comment]
Well would you allow other people to do that with your SDK? I don't know how this all works. a lot of people DO want a replacement for svencoop, and we could use your code as a base?

**Comment by SamVanheer** [comment]
There is nothing i can do to stop them. I'm not going to encourage them though.

**Comment by CryoKeen** [comment]
Multisource fixed thanks!

Does noclip or mp_allowmonsters 1 work in your mod? I had trouble getting them to work.

**Comment by SamVanheer** [comment]
Noclip only works in singleplayer due to engine level issues. It's implemented in the engine, which checks to see if the deathmatch setting is 0. I can trick it into thinking it's in singleplayer by setting it to 0, since i don't need the engine's variable to stay that way (i think). I'll look into getting that to work.

mp_allowmonsters works, but you can't set it in time to allow monsters to spawn. Only monster makers will work right now.

**Comment by SamVanheer** [comment]
I've added the option to use co-op gamerules. When starting a server, set sv_coop to either 1 or 2 to use co-op gamerules. See this thread for more information (scroll down a bit): http://twhl.info/forums.php?thread=19070&page=5

This is not intended to mimic Sven Co-op behavior, so if you want that, you'll have to wait until the Angelscript API has complete gamerules support. You'll be able to implement your own gamerules logic with co-op handling as you see fit. I'm sure somebody will write a complete gamerules class to mimic SC, i can't prevent that.
